### ISSUE TITLE
Syntax error !?

### ISSUE THREAD

**Issue by ghost** [ms32035/trading212-rest#1]
Hi, trying to use the code in a AWS Lambda function running Python 3.7
I get the below error. Would you know what it could be?

{
  "errorMessage": "Syntax error in module 'lambda_function': invalid syntax (lambda_function.py, line 70)",
  "errorType": "Runtime.UserCodeSyntaxError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\" Line 70\n            while next_page := response.get(\"nextPagePath\"):\n"
  ]
}

**Comment by ms32035** [comment]
Python 3.7 is way past EOL, and Walrus assignment was added in 3.8
